name: "Production CI"

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
 

  generate-java-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install protoc-gen-grpc-java
        uses: JacobSMoller/setup-protoc-grpc-java@v0.0.1

      - name: Generate Java code
        run: |
          mkdir -p build/java
          protoc -I=./contracts/proto --java_out=build/java --grpc-java_out=build/java $(find ./contracts/proto -type f -name '*.proto')
      - name: Upload generated Java client
        uses: actions/upload-artifact@v4
        with:
          name: java-client
          path: build/java

  publish-java-client:
    runs-on: ubuntu-latest
    needs: generate-java-client
    steps:
      - name: Download generated Java client
        uses: actions/download-artifact@v4
        with:
          name: java-client

      - name: Setup Java for publishing
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.TOKEN_GITHUB }}

      - name: Create directory structure
        run: |
          mkdir -p src/main/java
          mv com src/main/java
      - name: Create pom.xml
        run: |
          cat > pom.xml <<EOF
          <project xmlns="http://maven.apache.org/POM/4.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
          http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.zhunismp</groupId>
            <artifactId>proto-client</artifactId>
            <version>0.1.4</version>
            <packaging>jar</packaging>
            <distributionManagement>
              <repository>
                <id>github</id>
                <name>GitHub Packages</name>
                <url>https://maven.pkg.github.com/gowridurgad/mmp-contract</url>
              </repository>
            </distributionManagement>
            <dependencies>
              <dependency>
              <groupId>com.google.protobuf</groupId>
              <artifactId>protobuf-java</artifactId>
              <version>4.31.0</version>
              </dependency>
            </dependencies>
          </project>
          EOF
      - name: Tree
        run: tree .
      

      - name: Publish to GitHub Packages
        run: |
          mvn clean install
          mvn deploy -DskipTests -e -X
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
