name: "Production CI"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Installing protoc-gen-go
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generating protos
        run: |
          mkdir -p build/go
          protoc -I=./contracts/proto --go_out=build/go $(find ./contracts/proto -type f -name '*.proto')
      - name: Upload generated Go client
        uses: actions/upload-artifact@v4
        with:
          name: go-client
          path: build/go

  publish-go-client:
    runs-on: ubuntu-latest
    needs: generate-go-client
    steps:
      - name: Download generated Go client
        uses: actions/download-artifact@v4
        with:
          name: go-client
      - name: Release go pkg
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        