name: "Production CI"

on:
  push:
    branches:
      - master

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Installing protoc-gen-go
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generating protos
        run: |
          mkdir -p $GEN_OUT_DIR
          protoc -I=$PROTO_DIR \ 
          --go_out=$GEN_OUT_DIR \ 
          $(find $PROTO_DIR -type f -name '*.proto')          
        env:
          GEN_OUT_DIR: /build/go
          PROTO_DIR: contracts/proto